title: Education_ERP_help
optionalCategoryIndex: true
supportedLanguages: []
properties: []
code: ERP
link:
  name: Education_ERP_help
  pathname: github.com/Smile-Tech-Study/Education_ERP_help/main/-
  lastVisited: >-
    github.com/Smile-Tech-Study/Education_ERP_help/main/-/organizaciya-elektronnykh-platezhei/vozvrat-klientu-posle-onlain-oplaty
  logo: ero-logo (2).png
  title: Education_ERP_help
  query: {}
  group: null
  style: null
  description: null
  order: 999999
  isCloning: false
  cloneCancelDisabled: false
  redirectOnClone: null
relatedLinks: []
name: Education_ERP_help
repositoryName: Education_ERP_help
sourceName: github.com
userInfo:
  mail: massika24@gmail.com
  name: mariya-roldygina
  id: massika24@gmail.com
logo: ero-logo (2).png
logo_dark: erp-logo.svg
